advanced:
    cache_dir: ""
    cache_ttl: 3600
    debug: false
    editor: notepad
    max_concurrent: 5
api:
    base_url: https://api.github.com
    retry_count: 3
    retry_delay: 1
    timeout: 30
    upload_url: https://uploads.github.com
auth:
    client_id: Ov23lirRc5ncZbqzHOgH
    client_secret: e23e1eb3be1ebf95262e6d716b3444be43efcd9d
    scopes:
        - notifications
        - repo
        - user
    token_storage: file
display:
    compact_mode: false
    date_format: relative
    output_format: table
    show_emojis: true
    theme: light
notifications:
    auto_refresh: false
    default_filter: unread
    exclude_orgs: []
    exclude_repos: []
    exclude_types: []
    include_orgs: []
    include_repos: []
    include_types: []
    refresh_interval: 60
