# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GhNotif < Formula
  desc "A high-performance CLI tool for managing GitHub notifications"
  homepage "https://github.com/user/gh-notif"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/user/gh-notif/releases/download/v1.0.0/gh-notif_Darwin_arm64.tar.gz"
      sha256 "sha256-placeholder"

      def install
        bin.install "gh-notif"
        man1.install Dir["docs/man/*.1"]
        bash_completion.install "completions/gh-notif.bash" => "gh-notif"
        zsh_completion.install "completions/gh-notif.zsh" => "_gh-notif"
        fish_completion.install "completions/gh-notif.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/user/gh-notif/releases/download/v1.0.0/gh-notif_Darwin_x86_64.tar.gz"
      sha256 "sha256-placeholder"

      def install
        bin.install "gh-notif"
        man1.install Dir["docs/man/*.1"]
        bash_completion.install "completions/gh-notif.bash" => "gh-notif"
        zsh_completion.install "completions/gh-notif.zsh" => "_gh-notif"
        fish_completion.install "completions/gh-notif.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/user/gh-notif/releases/download/v1.0.0/gh-notif_Linux_arm64.tar.gz"
      sha256 "sha256-placeholder"

      def install
        bin.install "gh-notif"
        man1.install Dir["docs/man/*.1"]
        bash_completion.install "completions/gh-notif.bash" => "gh-notif"
        zsh_completion.install "completions/gh-notif.zsh" => "_gh-notif"
        fish_completion.install "completions/gh-notif.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/user/gh-notif/releases/download/v1.0.0/gh-notif_Linux_x86_64.tar.gz"
      sha256 "sha256-placeholder"

      def install
        bin.install "gh-notif"
        man1.install Dir["docs/man/*.1"]
        bash_completion.install "completions/gh-notif.bash" => "gh-notif"
        zsh_completion.install "completions/gh-notif.zsh" => "_gh-notif"
        fish_completion.install "completions/gh-notif.fish"
      end
    end
  end

  depends_on "git"

  test do
    system "#{bin}/gh-notif", "--version"
    system "#{bin}/gh-notif", "--help"
  end
end
